# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/eShopLite.WebApp /source/eShopLite.WebApp
COPY ./src/eShopLite.DataEntities /source/eShopLite.DataEntities

WORKDIR /source/eShopLite.WebApp

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "eShopLite.WebApp.dll"]
